# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
df=pd.read_csv("/Users/apetek/Desktop/Github/python-api-challenge/cities.csv")
df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,BÃ©boto,100,TD,1614817602,14,8.2668,16.9390,77.14,4.74
1,Kruisfontein,0,ZA,1614817348,91,-34.0033,24.7314,63.00,1.01
2,Castro,100,BR,1614817545,97,-24.7911,-50.0119,63.73,5.06
3,Hobart,75,AU,1614817318,37,-42.8794,147.3294,71.60,20.71
4,Mataura,9,NZ,1614817311,56,-46.1927,168.8643,61.00,8.01
5,Ancud,75,CL,1614817603,72,-41.8697,-73.8203,62.01,4.61
6,Tuatapere,29,NZ,1614817603,56,-46.1333,167.6833,61.00,8.01
7,Moyale,66,KE,1614817603,30,3.5167,39.0584,71.62,15.88
8,Dingle,54,PH,1614817603,83,10.9995,122.6711,79.02,10.74
9,Tura,0,IN,1614817603,27,25.5198,90.2201,62.83,3.51
10,Ushuaia,20,AR,1614817603,54,-54.8000,-68.3000,53.60,3.76
11,Qaanaaq,62,GL,1614817353,80,77.4840,-69.3632,-21.28,7.07
12,Taltal,29,CL,1614817593,78,-25.4000,-70.4833,67.17,4.70
13,Colgong,0,IN,1614817604,27,25.2667,87.2167,59.16,2.62
14,Bilibino,100,RU,1614817604,88,68.0546,166.4372,3.87,15.43
15,Port Hardy,90,CA,1614817604,87,50.6996,-127.4199,46.40,13.80
16,Rikitea,49,PF,1614817604,81,-23.1203,-134.9692,80.10,8.95
17,San Policarpo,48,PH,1614817604,84,12.1791,125.5072,79.63,13.44
18,Jamestown,90,US,1614817566,95,42.0970,-79.2353,34.00,7.16
19,Inhambane,41,MZ,1614817570,92,-23.8650,35.3833,73.98,6.08
20,Jackson,1,US,1614817605,24,42.4165,-122.8345,66.99,6.91
21,Tuktoyaktuk,75,CA,1614817323,69,69.4541,-133.0374,-20.20,5.75
22,Yellowknife,40,CA,1614817385,65,62.4560,-114.3525,-0.40,10.36
23,Anloga,40,GH,1614817605,84,5.7947,0.8973,84.20,13.80
24,Pangnirtung,90,CA,1614817605,77,66.1451,-65.7125,-4.00,6.91
25,Khatanga,0,RU,1614817454,78,71.9667,102.5000,-37.89,6.58
26,Cherskiy,100,RU,1614817356,90,68.7500,161.3000,-8.32,11.34
27,Ostrovnoy,100,RU,1614817581,88,68.0531,39.5131,16.72,13.18
28,Bathsheba,40,BB,1614817361,69,13.2167,-59.5167,78.80,17.27
29,Albany,90,US,1614817606,60,42.6001,-73.9662,39.20,8.05
30,Hermanus,95,ZA,1614817606,89,-34.4187,19.2345,66.99,7.85
31,Solnechnyy,97,RU,1614817606,92,50.7214,136.6319,13.60,5.73
32,Verkhnetulomskiy,75,RU,1614817606,93,68.6073,31.7962,19.40,6.71
33,Hilo,1,US,1614817392,44,19.7297,-155.0900,78.80,11.50
34,Busselton,96,AU,1614817606,93,-33.6500,115.3333,68.00,3.00
35,Prince Rupert,90,CA,1614817437,87,54.3161,-130.3201,41.00,10.36

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
counter=0
g_key
for d in df:
    if counter == 5:
        break

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure